version: '2.3'

services:

  my_container:
    image: my_image
    container_name: my_container
    working_dir: /code
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      - PYTHONPATH=/code/src
      - DISPLAY=unix$DISPLAY
    ports:
     - "8888:8888"
    volumes:
      - ../:/code
      - /tmp/.X11-unix:/tmp/.X11-unix
    runtime: nvidia
    command: tail /dev/null -f
